spring:
  application:
    name: competencyservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/competencyservice
      username: root
      password: root
  config:
    import: optional:configserver:http://localhost:8071/
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8787

management:
  endpoints:
    web:
      exposure:
        include: "*"

