spring:
  application:
    name: training-time-slot-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/trainingtimeslotservice
      username: root
      password: root
  config:
    import: optional:configserver:http://localhost:8071/
server:
  port: 8686

management:
  endpoints:
    web:
      exposure:
        include: '*'