spring:
  application:
    name: trainingtimeslotservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/trainingtimeslotservice
      username: root
      password: root
  config:
    import: optional:configserver:http://localhost:8071/
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8686

management:
  endpoints:
    web:
      exposure:
        include: '*'