spring:
  application:
    name: "company-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3399/companymicroservice
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: '*'
