spring:
  application:
    name: "companyservice"
  profiles:
    active: "prod"
  datasource:
#    url: jdbc:mysql://localhost:3399/companymicroservice
    url: jdbc:mysql://localhost:3306/companyservicedb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: '*'
