spring:
  application:
    name: "companyservice"
#  profiles:
#    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3306/companyservicedb
    username: root
    password: root
#  sql:
#    init:
#      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: '*'
