spring:
  application:
    name: "designation-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3399/designationservice
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8484
