spring:
  application:
    name: "designationservice"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/designationservice
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: 'localhost'
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8484

management:
  endpoints:
    web:
      exposure:
        include: '*'