spring:
  application:
    name: training-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/trainingservice
      username: root
      password: root
  config:
    import: optional:configserver:http://localhost:8071/
server:
  port: 8585
management:
  endpoints:
    web:
      exposure:
        include: '*'
