server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Yashpalgawali/training-tracker-microservice-config.git"
          clone-on-start: true
          default-label: main
          timeout: 5
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///E://training tracker microservice config//config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

